<?xml version="1.0" encoding="utf-8"?><Database Name="TRG" Class="workDbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SQL-SERVER;Initial Catalog=TRG;Integrated Security=True" SettingsObjectName="AppServices.Properties.Settings" SettingsPropertyName="TRGConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Blog" Member="Blogs">
    <Type Name="Blog">
      <Column Name="bId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="bSId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bSubject" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="bContent" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="bLastEdited" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="bPosted" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="bDeleted" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="uId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="uSId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="uTId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="uLastLogin" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Course" Member="Courses">
    <Type Name="Course">
      <Column Name="cId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Dashboard" Member="Dashboards">
    <Type Name="Dashboard">
      <Column Name="dId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="dUId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dItemID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dItemType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dTimestamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="dNotification" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="dViewed" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.FileUpload" Member="FileUploads">
    <Type Name="FileUpload">
      <Column Name="fuId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fuMsId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fuFileName" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="fuExtention" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="fuSize" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fuPath" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="fuTimestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="fuCanSystemRead" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Meeting" Member="Meetings">
    <Type Name="Meeting">
      <Column Name="mId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="mSId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="mMsId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="mPreviousRequestID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="mWeek" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="mAttended" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="mStudentMinutes" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="mTutorMinutes" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="mRequestStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MeetingComment" Member="MeetingComments">
    <Type Name="MeetingComment">
      <Column Name="mcId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="mcUId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="mcMId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="mcComment" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="mcTimestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="mcDelete" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MeetingSlot" Member="MeetingSlots">
    <Type Name="MeetingSlot">
      <Column Name="msId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="msTId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="msDay" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="msSlot" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Message" Member="Messages">
    <Type Name="Message">
      <Column Name="mId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="mSubject" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="mContent" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="mTimestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="mPreviousMId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Module" Member="Modules">
    <Type Name="Module">
      <Column Name="mID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="mCId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="mName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="mLevel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="mCredits" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ModuleStudent" Member="ModuleStudents">
    <Type Name="ModuleStudent">
      <Column Name="msId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="msSId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="msMtId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ModuleTutor" Member="ModuleTutors">
    <Type Name="ModuleTutor">
      <Column Name="mtId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="mtMId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="mtTId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Participant" Member="Participants">
    <Type Name="Participant">
      <Column Name="pId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="pTId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="pSId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="pMId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="pSender" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="pDeleted" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Student" Member="Students">
    <Type Name="Student">
      <Column Name="sId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="sTId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sCId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sForename" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="sSurname" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="sEmail" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="sYear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sPassword" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Tutor" Member="Tutors">
    <Type Name="Tutor">
      <Column Name="tId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tForename" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="tSurname" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="tEmail" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tAdmin" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tPassword" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="tRoom" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UploadComment" Member="UploadComments">
    <Type Name="UploadComment">
      <Column Name="ucId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ucFuId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ucUId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ucComment" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ucTimestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ucDelete" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>